import { ALL_TRAITS } from "../lib/traits/traitDatabase";
import { interpretAllTraits } from "../lib/traits/interpreter";

// Hand-picked compound genotypes for a varied, interesting demo.
const fixed: Record<string, string> = {
  rs1801133: "AG", rs1801131: "TT",   // MTHFR mildly reduced
  rs429358: "TT", rs7412: "CT",       // APOE E2/E3
  rs713598: "GG", rs1726866: "AA", rs10246939: "CC", // TAS2R38 super taster
};
const snps = new Map<string, string>(Object.entries(fixed));
ALL_TRAITS.forEach((t, i) => {
  if (t.isCompound) return;
  const rs = t.rsids[0];
  if (snps.has(rs)) return;
  const v = t.variants[i % t.variants.length];
  snps.set(rs, v.genotype);
});
const results = interpretAllTraits(snps);
const missing = ALL_TRAITS.filter(t => !results.find(r => r.trait.id === t.id)).map(t => t.id);
const uncommon = results.filter(r => r.interpretation.label === "Uncommon Variant").map(r => r.trait.id);
console.error({ traits: ALL_TRAITS.length, results: results.length, missing, uncommon, colors: results.reduce((a, r) => (a[r.interpretation.color] = (a[r.interpretation.color] || 0) + 1, a), {} as Record<string, number>) });
const entries = [...snps.entries()].map(([k, v]) => `  ["${k}", "${v}"],`).join("\n");
process.stdout.write(`// Auto-generated by scripts/gen-sample-genome.ts — a synthetic genome used for demo mode.\n// These genotypes are illustrative only and do not belong to a real person.\n\nexport const SAMPLE_GENOME_ENTRIES: [string, string][] = [\n${entries}\n];\n\nexport function getSampleGenome(): Map<string, string> {\n  return new Map(SAMPLE_GENOME_ENTRIES);\n}\n`);
