"use client";

import { useEffect, useState } from "react";
import { useReducedMotion } from "motion/react";
import { FileDown, Cpu, Sparkles, Check } from "lucide-react";
import Reveal from "@/components/ui/Reveal";

const LOG_LINES = [
  ["rs4680", "chr22", "19951271", "GG", true],
  ["rs762551", "chr15", "75041917", "AA", true],
  ["rs1815739", "chr11", "66328095", "CT", true],
  ["rs9939609", "chr16", "53820527", "AT", false],
  ["rs12913832", "chr15", "28365618", "GG", true],
  ["rs1801133", "chr1", "11856378", "AG", true],
  ["rs4988235", "chr2", "136608646", "TT", true],
  ["rs6265", "chr11", "27679916", "CC", true],
  ["rs7412", "chr19", "45412079", "CT", true],
  ["rs2802292", "chr6", "108587315", "GT", true],
] as const;

function ParserLog() {
  const reduced = useReducedMotion();
  const [tick, setTick] = useState(0);
  useEffect(() => {
    if (reduced) return;
    const id = setInterval(() => setTick((t) => t + 1), 900);
    return () => clearInterval(id);
  }, [reduced]);

  const visible = Array.from({ length: 5 }, (_, i) => LOG_LINES[(tick + i) % LOG_LINES.length]);

  return (
    <div className="font-mono text-[11px] leading-6 rounded-xl bg-black/40 border border-[var(--color-glass-border)] p-3 overflow-hidden">
      <div className="flex items-center gap-1.5 mb-2 opacity-60">
        <span className="w-2 h-2 rounded-full bg-red-400/70" /><span className="w-2 h-2 rounded-full bg-yellow-400/70" /><span className="w-2 h-2 rounded-full bg-green-400/70" />
        <span className="ml-2 text-[10px]">parser · chunk {(tick % 61) + 1}/61</span>
      </div>
      {visible.map(([rsid, chr, pos, gt, kept], i) => (
        <div key={`${rsid}-${i}`} className={`flex gap-3 ${i === 4 ? "text-[var(--color-foreground)]" : "text-[var(--color-muted)]"}`}>
          <span className="w-20">{rsid}</span>
          <span className="w-10">{chr}</span>
          <span className="w-20 hidden sm:inline">{pos}</span>
          <span className="w-6">{gt}</span>
          <span className={kept ? "text-[var(--color-neon)]" : "opacity-40"}>{kept ? "✓ kept" : "· skip"}</span>
        </div>
      ))}
    </div>
  );
}

const STEPS = [
  {
    icon: FileDown,
    title: "Export your raw data",
    body: "Download the raw genotype file from 23andMe or AncestryDNA. It's a plain text file with ~600,000 rows — one per marker.",
    visual: (
      <div className="rounded-xl bg-black/40 border border-[var(--color-glass-border)] p-3 font-mono text-[11px] leading-6 text-[var(--color-muted)]">
        <div># This data file generated by 23andMe</div>
        <div># rsid&nbsp;&nbsp;chromosome&nbsp;&nbsp;position&nbsp;&nbsp;genotype</div>
        <div className="text-[var(--color-foreground)]/80">rs548049170&nbsp;&nbsp;1&nbsp;&nbsp;69869&nbsp;&nbsp;TT</div>
        <div className="text-[var(--color-foreground)]/80">rs13328684&nbsp;&nbsp;1&nbsp;&nbsp;74792&nbsp;&nbsp;--</div>
        <div className="text-[var(--color-foreground)]/80">rs9283150&nbsp;&nbsp;1&nbsp;&nbsp;565508&nbsp;&nbsp;AA</div>
        <div className="opacity-50">… 600,000 more rows</div>
      </div>
    ),
  },
  {
    icon: Cpu,
    title: "Parsed on your device",
    body: "A streaming parser reads the file in 10,000-line chunks in your browser tab. Only the 44 trait-relevant rsIDs are kept; everything else is discarded in memory.",
    visual: <ParserLog />,
  },
  {
    icon: Sparkles,
    title: "Read your traits",
    body: "Each genotype is matched to a curated interpretation: what it's associated with, practical tips, and the PubMed studies behind it.",
    visual: (
      <div className="rounded-xl bg-black/40 border border-[var(--color-glass-border)] p-3 space-y-2">
        {[
          ["CYP1A2", "Caffeine metabolism", "Fast metabolizer", "green"],
          ["PER2", "Chronotype", "Night owl", "purple"],
          ["ACTN3", "Muscle fiber type", "Power / sprint", "red"],
        ].map(([gene, name, label, color]) => (
          <div key={gene} className="flex items-center justify-between gap-3 text-xs">
            <span className="flex items-center gap-2 min-w-0">
              <Check className="w-3.5 h-3.5 text-[var(--color-neon)] shrink-0" />
              <span className="font-mono text-[var(--color-muted)]">{gene}</span>
              <span className="truncate">{name}</span>
            </span>
            <span className={`badge-${color} px-2 py-0.5 rounded-full text-[10px] font-medium whitespace-nowrap`}>{label}</span>
          </div>
        ))}
      </div>
    ),
  },
];

export default function HowItWorks() {
  return (
    <section id="how-it-works" className="py-24 sm:py-32 px-5 sm:px-8 scroll-mt-16">
      <div className="max-w-7xl mx-auto">
        <Reveal className="max-w-2xl mb-14">
          <p className="eyebrow mb-3">How it works</p>
          <h2 className="text-3xl sm:text-5xl font-semibold">Three steps. Nothing leaves your tab.</h2>
          <p className="mt-4 text-[var(--color-muted)] text-lg">
            The whole pipeline — detection, parsing, interpretation — runs client-side. The server only ever sees a login.
          </p>
        </Reveal>

        <ol className="grid md:grid-cols-3 gap-5">
          {STEPS.map((s, i) => (
            <Reveal key={s.title} delay={i * 0.1}>
              <li className="glass-card is-interactive p-6 h-full flex flex-col">
                <div className="flex items-center justify-between mb-5">
                  <span className="w-11 h-11 rounded-xl bg-[rgba(143,124,255,0.1)] border border-[rgba(143,124,255,0.2)] flex items-center justify-center">
                    <s.icon className="w-5 h-5 text-[var(--color-neon)]" />
                  </span>
                  <span className="font-mono text-xs text-[var(--color-muted)]">0{i + 1}</span>
                </div>
                <h3 className="text-xl font-semibold mb-2">{s.title}</h3>
                <p className="text-sm text-[var(--color-muted)] leading-relaxed mb-6">{s.body}</p>
                <div className="mt-auto">{s.visual}</div>
              </li>
            </Reveal>
          ))}
        </ol>
      </div>
    </section>
  );
}
